# 분류 예측의 불확실성 추정
- 분류기의 예측의 불확실성을 추정할 수 있는 기능
- decision_function, predict_proba

decision_function

In [10]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.datasets import make_circles
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt

In [2]:
X, y = make_circles(noise=0.25, factor=0.5, random_state=1)

In [11]:
y_named = np.array(["blue","red"])[y]
X_train, X_test, y_train_named, y_test_named, y_train, y_test = \
    train_test_split(X,y_named, y, random_state=0)

In [12]:
gbrt = GradientBoostingClassifier(random_state=0)
gbrt.fit(X_train, y_train_named)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='auto',
                           random_state=0, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [14]:
print("X_Test shape:", X_test.shape)
print("decision function return shape:",gbrt.decision_function(X_test).shape)

X_Test shape: (25, 2)
decision function return shape: (25,)


In [15]:
gbrt.decision_function(X_test)

array([ 4.13592629, -1.7016989 , -3.95106099, -3.62599351,  4.28986668,
        3.66166106, -7.69097177,  4.11001634,  1.10753883,  3.40782247,
       -6.46262729,  4.28986668,  3.90156371, -1.20031192,  3.66166106,
       -4.17231209, -1.23010022, -3.91576275,  4.03602808,  4.11001634,
        4.11001634,  0.65708962,  2.69826291, -2.65673325, -1.86776597])

In [18]:
# 이진 분류에서 decision_function은 (n_samples,) 만큼의 값을 return한다.
# 다중 분류에서 decision_function의 결과값의 크기는 (n_samples, n_classes)
# 각 sample당 실수값을 하나씩 반환하며, 이진분류에서 각 실수값은 클래스1에 속한다고 믿는 정도를 의미
print("decision function:\n",gbrt.decision_function(X_test)[:6])

decision function:
 [ 4.13592629 -1.7016989  -3.95106099 -3.62599351  4.28986668  3.66166106]


In [19]:
print(gbrt.decision_function(X_test)>0)
print(gbrt.predict(X_test))

[ True False False False  True  True False  True  True  True False  True
  True False  True False False False  True  True  True  True  True False
 False]
['red' 'blue' 'blue' 'blue' 'red' 'red' 'blue' 'red' 'red' 'red' 'blue'
 'red' 'red' 'blue' 'red' 'blue' 'blue' 'blue' 'red' 'red' 'red' 'red'
 'red' 'blue' 'blue']


predict_proba

In [22]:
print("predict_proba return shape:",gbrt.predict_proba(X_test).shape)
# 이진 분류에서 predict_proba의 경우 항상 (n_samples,2)
# 다중 분류에서 predict_proba의 결과값의 크기는 (n_samples, n_classes)
# 각 출력값은 해당 클래스에 속할 확률을 의미

predict_proba return shape: (25, 2)


In [23]:
print("decision function:\n",gbrt.predict_proba(X_test)[:6])

decision function:
 [[0.01573626 0.98426374]
 [0.84575649 0.15424351]
 [0.98112869 0.01887131]
 [0.97406775 0.02593225]
 [0.01352142 0.98647858]
 [0.02504637 0.97495363]]
