# 데이터 표현
- 특성(feature)은 범주형 특성(categorical feature)와 연속형특성(continuous feature)이 있다.
- 특성 공학(feature engineering)이란 특정 애플리케이션에 가장 적합한 데이터 표현을 찾는 것
- 데이터 표현에 따라 모델의 성능이 달라짐

1. 범주형 특성


- 범주형 특성은 연속적이지 않은 특성.(이산적)
- 보통 문자로 표시되나, 숫자로 표현된 것도 범주형 특성일 수 있음.
- 범주형 특성은 one-hot-encoding 방식으로 많이 표현됨.
- one-hot-encoding = one-out-of-N encoding = dummy variable
- 위 방식은 범주마다 하나의 특성으로 간주하고 그 결과값을 0 or 1로 표현하는 것.
- 0과 1로 표현된 변수는 모든 모델에 적용 가능하므로 좋다.
- pandas의 get_dummies 함수를 통해 데이터를 쉽게 위와 같은 방법으로 인코딩 할 수 있다.


- 범주형 특성의 경우 오타가 있을 수 있고 같은 내용을 다르게 표현할 수 있으므로 데이터 가공 전 이에 대한 확인이 필수
- 이를 확인하기에 좋은 것이 Series의 value_counts 매서드임. (dataframe의 각 열은 Series)


In [1]:
import pandas as pd
df = pd.DataFrame({'숫자특성':[0,1,2,1], '범주형 특성':['a','b','c','b']})
display(df)
display(pd.get_dummies(df))
display(pd.get_dummies(df,columns=['숫자특성', '범주형 특성']))
df['숫자특성'] = df['숫자특성'].astype(str)
display(pd.get_dummies(df))

In [7]:
import os
import mglearn
data = pd.read_csv(os.path.join(mglearn.datasets.DATA_PATH, "adult.data"), header=None, index_col=False)

In [11]:
data

0                  1       2              3   4   \
0      39          State-gov   77516      Bachelors  13   
1      50   Self-emp-not-inc   83311      Bachelors  13   
2      38            Private  215646        HS-grad   9   
3      53            Private  234721           11th   7   
4      28            Private  338409      Bachelors  13   
5      37            Private  284582        Masters  14   
6      49            Private  160187            9th   5   
7      52   Self-emp-not-inc  209642        HS-grad   9   
8      31            Private   45781        Masters  14   
9      42            Private  159449      Bachelors  13   
10     37            Private  280464   Some-college  10   
11     30          State-gov  141297      Bachelors  13   
12     23            Private  122272      Bachelors  13   
13     32            Private  205019     Assoc-acdm  12   
14     40            Private  121772      Assoc-voc  11   
15     34            Private  245487        7th-8th   4   
16     25   Self-emp-not-inc  176756        HS-grad   9   
17     32            Private  186824        HS-grad   9   
18     38            Private   28887           11th   7   
19     43   Self-emp-not-inc  292175        Masters  14   
20     40            Private  193524      Doctorate  16   
21     54            Private  302146        HS-grad   9   
22     35        Federal-gov   76845            9th   5   
23     43            Private  117037           11th   7   
24     59            Private  109015        HS-grad   9   
25     56          Local-gov  216851      Bachelors  13   
26     19            Private  168294        HS-grad   9   
27     54                  ?  180211   Some-college  10   
28     39            Private  367260        HS-grad   9   
29     49            Private  193366        HS-grad   9   
...    ..                ...     ...            ...  ..   
32531  30                  ?   33811      Bachelors  13   
32532  34            Private  204461      Doctorate  16   
32533  54            Private  337992      Bachelors  13   
32534  37            Private  179137   Some-college  10   
32535  22            Private  325033           12th   8   
32536  34            Private  160216      Bachelors  13   
32537  30            Private  345898        HS-grad   9   
32538  38            Private  139180      Bachelors  13   
32539  71                  ?  287372      Doctorate  16   
32540  45          State-gov  252208        HS-grad   9   
32541  41                  ?  202822        HS-grad   9   
32542  72                  ?  129912        HS-grad   9   
32543  45          Local-gov  119199     Assoc-acdm  12   
32544  31            Private  199655        Masters  14   
32545  39          Local-gov  111499     Assoc-acdm  12   
32546  37            Private  198216     Assoc-acdm  12   
32547  43            Private  260761        HS-grad   9   
32548  65   Self-emp-not-inc   99359    Prof-school  15   
32549  43          State-gov  255835   Some-college  10   
32550  43   Self-emp-not-inc   27242   Some-college  10   
32551  32            Private   34066           10th   6   
32552  43            Private   84661      Assoc-voc  11   
32553  32            Private  116138        Masters  14   
32554  53            Private  321865        Masters  14   
32555  22            Private  310152   Some-college  10   
32556  27            Private  257302     Assoc-acdm  12   
32557  40            Private  154374        HS-grad   9   
32558  58            Private  151910        HS-grad   9   
32559  22            Private  201490        HS-grad   9   
32560  52       Self-emp-inc  287927        HS-grad   9   

                           5                   6                7   \
0               Never-married        Adm-clerical    Not-in-family   
1          Married-civ-spouse     Exec-managerial          Husband   
2                    Divorced   Handlers-cleaners    Not-in-family   
3          Married-civ-spouse   Handlers-cleaners          Husband  

In [12]:
data[9].value_counts()

 Male      21790
 Female    10771
Name: 9, dtype: int64

In [13]:
data_dummies = pd.get_dummies(data)

In [14]:
data_dummies

0       2   4     10    11  12  1_ ?  1_ Federal-gov  1_ Local-gov  \
0      39   77516  13   2174     0  40     0               0             0   
1      50   83311  13      0     0  13     0               0             0   
2      38  215646   9      0     0  40     0               0             0   
3      53  234721   7      0     0  40     0               0             0   
4      28  338409  13      0     0  40     0               0             0   
5      37  284582  14      0     0  40     0               0             0   
6      49  160187   5      0     0  16     0               0             0   
7      52  209642   9      0     0  45     0               0             0   
8      31   45781  14  14084     0  50     0               0             0   
9      42  159449  13   5178     0  40     0               0             0   
10     37  280464  10      0     0  80     0               0             0   
11     30  141297  13      0     0  40     0               0             0   
12     23  122272  13      0     0  30     0               0             0   
13     32  205019  12      0     0  50     0               0             0   
14     40  121772  11      0     0  40     0               0             0   
15     34  245487   4      0     0  45     0               0             0   
16     25  176756   9      0     0  35     0               0             0   
17     32  186824   9      0     0  40     0               0             0   
18     38   28887   7      0     0  50     0               0             0   
19     43  292175  14      0     0  45     0               0             0   
20     40  193524  16      0     0  60     0               0             0   
21     54  302146   9      0     0  20     0               0             0   
22     35   76845   5      0     0  40     0               1             0   
23     43  117037   7      0  2042  40     0               0             0   
24     59  109015   9      0     0  40     0               0             0   
25     56  216851  13      0     0  40     0               0             1   
26     19  168294   9      0     0  40     0               0             0   
27     54  180211  10      0     0  60     1               0             0   
28     39  367260   9      0     0  80     0               0             0   
29     49  193366   9      0     0  40     0               0             0   
...    ..     ...  ..    ...   ...  ..   ...             ...           ...   
32531  30   33811  13      0     0  99     1               0             0   
32532  34  204461  16      0     0  60     0               0             0   
32533  54  337992  13      0     0  50     0               0             0   
32534  37  179137  10      0     0  39     0               0             0   
32535  22  325033   8      0     0  35     0               0             0   
32536  34  160216  13      0     0  55     0               0             0   
32537  30  345898   9      0     0  46     0               0             0   
32538  38  139180  13  15020     0  45     0               0             0   
32539  71  287372  16      0     0  10     1               0             0   
32540  45  252208   9      0     0  40     0               0             0   
32541  41  202822   9      0     0  32     1               0             0   
32542  72  129912   9      0     0  25     1               0             0   
32543  45  119199  12      0     0  48     0               0             1   
32544  31  199655  14      0     0  30     0               0             0   
32545  39  111499  12      0     0  20     0               0             1   
32546  37  198216  12      0     0  40     0               0             0   
32547  43  260761   9      0     0  40     0               0             0   
32548  65   99359  15   1086     0  60     0               0             0   
32549  43  255835  10      0     0  40     0               0             0   
32550  43   27242  10      0  

In [17]:
features = data_dummies.iloc[:,0:-2]

In [22]:
X = features.values
y = data_dummies['14_ >50K'].values

In [23]:
X.shape

(32561, 108)

In [24]:
features.shape

(32561, 108)

In [25]:
y.shape

(32561,)

In [26]:
data_dummies['14_ >50K'].shape

(32561,)

- 숫자로 표현된 범주형 특성은 연속형으로 간주하여 get_dummies에서 가변수를 만들어 주지 않는다.
- 따라서 get_dummies에서 columns로 지정을 해주거나, type을 str로 변경해주어야한다.

In [27]:
import pandas as pd
df = pd.DataFrame({'숫자특성':[0,1,2,1], '범주형 특성':['a','b','c','b']})
display(df)

숫자특성 범주형 특성
0     0      a
1     1      b
2     2      c
3     1      b

In [28]:
display(pd.get_dummies(df))

숫자특성  범주형 특성_a  범주형 특성_b  범주형 특성_c
0     0         1         0         0
1     1         0         1         0
2     2         0         0         1
3     1         0         1         0

In [29]:
display(pd.get_dummies(df,columns=['숫자특성', '범주형 특성']))

숫자특성_0  숫자특성_1  숫자특성_2  범주형 특성_a  범주형 특성_b  범주형 특성_c
0       1       0       0         1         0         0
1       0       1       0         0         1         0
2       0       0       1         0         0         1
3       0       1       0         0         1         0

In [30]:
df['숫자특성'] = df['숫자특성'].astype(str)
display(pd.get_dummies(df))

숫자특성_0  숫자특성_1  숫자특성_2  범주형 특성_a  범주형 특성_b  범주형 특성_c
0       1       0       0         1         0         0
1       0       1       0         0         1         0
2       0       0       1         0         0         1
3       0       1       0         0         1         0

- sklearn을 이용한 범주형 데이터 인코딩
    - OneHotEncoder

In [31]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse=False)
#sparse를 False로 하면 OneHotEncoder가 희소 행렬이 아니라 Numpy 배열을 반환

In [32]:
ohe2 = OneHotEncoder()

In [34]:
print(ohe.fit_transform(df))

[[1. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1.]
 [0. 1. 0. 0. 1. 0.]]


In [37]:
print(ohe2.fit_transform(df))

  (0, 0)	1.0
  (0, 3)	1.0
  (1, 1)	1.0
  (1, 4)	1.0
  (2, 2)	1.0
  (2, 5)	1.0
  (3, 1)	1.0
  (3, 4)	1.0


In [39]:
#OneHotEncoder의 출력은 Dataframe이 아니라 array. 따라서 열의 이름이 없다. 열의 이름을 나타내기 위해서는 get_feature_names이용
print(ohe.get_feature_names())

['x0_0' 'x0_1' 'x0_2' 'x1_a' 'x1_b' 'x1_c']


- OneHotEncoder는 모든 feature가 범주형일 때 적용 가능.
- 연속형과 범주형이 섞여있을 때는 ColumnTransformer 이용
- ColumnTransformer는 열마다 다른 변환 적용 가능

In [40]:
data = pd.read_csv(os.path.join(mglearn.datasets.DATA_PATH, "adult.data"), header=None, index_col=False,
                  names=['age','workclass','fnlwgt','education','education-num','marital-status','occupation','relationship',
                        'race','gender','capital-gain','capital-loss','hours-per-week','native-country','income'])

In [43]:
data = data[['age','hours-per-week','workclass','education','gender','occupation','income']]

In [44]:
#age와 hours-per-week는 연속형 데이터
#나머지는 범주형 데이터->OneHotEncoder

from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer([("scaling",StandardScaler(), ['age','hours-per-week']),
                       ("onehot",OneHotEncoder(sparse=False),['workclass','education','gender','occupation'])])

In [45]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

data_features = data.drop("income",axis=1)

In [46]:
X_train, X_test, y_train, y_test = train_test_split(data_features, data.income, random_state=0)

In [47]:
ct.fit(X_train)

ColumnTransformer(n_jobs=None, remainder='drop', sparse_threshold=0.3,
                  transformer_weights=None,
                  transformers=[('scaling',
                                 StandardScaler(copy=True, with_mean=True,
                                                with_std=True),
                                 ['age', 'hours-per-week']),
                                ('onehot',
                                 OneHotEncoder(categorical_features=None,
                                               categories=None, drop=None,
                                               dtype=<class 'numpy.float64'>,
                                               handle_unknown='error',
                                               n_values=None, sparse=False),
                                 ['workclass', 'education', 'gender',
                                  'occupation'])],
                  verbose=False)

In [49]:
X_train_trans = ct.transform(X_train)
print(X_train_trans.shape)

(24420, 44)


In [50]:
logreg = LogisticRegression(max_iter=1000)
logreg.fit(X_train_trans,y_train)
X_test_trans = ct.transform(X_test)
print("test score:{:.2f}".format(logreg.score(X_test_trans,y_test)))

C:\Users\minuk\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


test score:0.81
